name: Deployment
on:
  push:
    branches:
      - source
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.18.3]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: |
        npm install -g hexo
        npm install
    - name: Generate page
      run: |
        hexo g
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        deploy_key: ${{ secrets.GIT_PAGE_TOKEN }}
        publish_dir: ./public
        publish_branch: main
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot].noreply.github.com'
        commit_message: 'Deploy commit: ${{ github.event.head_commit.message }}'